name: flutter_location_picker
description: select position.
version: 0.0.1+1

author: chengda <mada502@126.com>
homepage: https://github.com/best-flutter/flutter_location_picker
documentation: https://github.com/best-flutter/flutter_location_picker

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.4.1 <1.0.0"